[mainConfig]
appName = "GopherAI"
host = "0.0.0.0"
port = 9090

[emailConfig]
authcode = "fxrtlgwuebwzjejg"
email = "1139517119@qq.com"

[redisConfig]
host = "127.0.0.1"
port = 6379
password = ""
db = 0

[mysqlConfig]
host = "127.0.0.1"
port = 3306
user = "root"
password = "root"
databaseName = "HaiAI"
charset =  "utf8mb4"

[jwtConfig]
 expire_duration= 168
 issuer= "huanheart"
 subject= "HaiAI"
 key= "HaiAI"

 [rabbitmqConfig]
  host= "127.0.0.1"
  port= 5672
  username= "root"
  password= "123456"
  vhost= "/"

[aiModel]
apiKey="sk-6e277f0001ca4714b3f96125b5e3910c"
